In [ ]:
#Question No 1
# Create a numpy array starting from 2 till 50 with a stepsize of 3.

import numpy as np #import numpy library with alias

arr = np.arange(2,50,3) #Creating a numpy array which Starts from 2, End at 50 with interval of 3
print (arr)



[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:
#Question No 2
#Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

import numpy as np

list1 = []
for i in range(0,5):
  n = int(input("Enter the element in List1 : ")) #Accept 5 Input from User
  list1.append(n)
  arr1=np.array(list1) # Converting to numpy array

list2 = []
for i in range(0,5):
  m = int(input("Enter the element in List2 : ")) #Accept 5 Input from User
  list2.append(m)
  arr2=np.array(list2) # Converting to numpy array

arr=np.concatenate((arr1, arr2)) # Concanating Both the numpy array
arr.sort() # Sorting
print(type(arr))
print("The Final Concanated & sorted numpy array: ",arr) # Printing Final Result

Enter the element in List1 : 0
Enter the element in List1 : 9
Enter the element in List1 : 8
Enter the element in List1 : 7
Enter the element in List1 : 6
Enter the element in List2 : 5
Enter the element in List2 : 4
Enter the element in List2 : 3
Enter the element in List2 : 2
Enter the element in List2 : 1
<class 'numpy.ndarray'>
The Final Concanated & sorted numpy array:  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Question No 3
#Write a code snippet to find the dimensions of a ndarray and its size.

import numpy as np

a = np.array([2,3,4,5,6])
print(type(a))

print (a.size)   # output: 5
print (a.ndim)  # output: 1
print (a.shape)  # output: (5, )

<class 'numpy.ndarray'>
5
1
(5,)


In [ ]:
#Question No 4
#How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
#Hint: np.newaxis, np.expand_dims

import numpy as np

a = np.array([1,2,3,4,5])
print (a.shape)    # 1D numpy array output: (5,)

a2 = a [np.newaxis, :]
print (a2.shape)    # Converting 1D to 2D numpy array using np.newaxis output: (1,5)

a3 = np.expand_dims (a, axis=1)
print (a3.shape)    # Converting 1D to 2D numpy array using np.expand_dim output: (5,1) will add an axis at index position 1#

(5,)
(1, 5)
(5, 1)


In [ ]:
#Question No 5
#Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

import numpy as np

a = np.array ([[1,2], [3,4]])
b = np.array ([[5,6], [7,8]])

print ("Vertically Stacked:\n", np.vstack((a,b)))
print ("Horizontaly Stacked:\n", np.hstack((a,b)))

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontaly Stacked:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Question No 6
#How to get unique items and counts of unique items?

a = [2,3,4,4,5,6,6,6,7,8,8,9,0]

l=[]
count = 0

for i in a:
  if i not in l:
    count += 1
    l.append(i)

print ("Unique item count is:", count)
print ("Unique item are:", l)



Unique item count is: 9
Unique item are: [2, 3, 4, 5, 6, 7, 8, 9, 0]
